<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2017/04/18 09:52:21
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
