<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
    public function getActiveJobs($max = 10)
    {
        $q = $this->getActiveJobsQuery()->limit($max);
        
        return $q->execute();
        /*
        // old code
        $q = Doctrine_Query::create()
        ->from('JobeetJob j')
        ->where('j.category_id = ?', $this->getId())
        ->limit($max);
        
        return Doctrine_Core::getTable('JobeetJob')->getActiveJobs($q);
        */
    }
    
    /*
    // sluaggable column added in /config/doctrine/schena.yml so no need this function
    public function getSlug()
    {
        return jobeet::slugify($this->getName());
    }
    */
    
    public function countActiveJobs()
    {
        return $this->getActiveJobsQuery()->count();
        /*
        $q = Doctrine_Query::create()
        ->from('JobeetJob j')
        ->where('j.category_id = ?', $this->getId());
        
        return Doctrine_Core::getTable('JobeetJob')->countActiveJobs($q);
        */
    }
    
    public function getActiveJobsQuery()
    {
        $q = Doctrine_Query::create()
        ->from('JobeetJob j')
        ->where('j.category_id = ?', $this->getId());
        
        return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($q);
    }
    
    public function getLatestPost()
    {
        return $this->getActiveJobs(1)->getFirst();
    }
}
