<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/04/22 12:21:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'aumaum',
  'name' => 'doctrine',
)),);
