<?php
// auto-generated by sfCacheConfigHandler
// date: 2017/04/27 12:10:19
$this->addCache($moduleName, '_language', array('withLayout' => false, 'lifeTime' => 86400, 'clientLifeTime' => 86400, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

